base_url = "https://willemvanhulle.tech"
author = "Willem Vanhulle"
title = "Willem Vanhulle"


compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags", description = "Tags" }]

[markdown]

# Navigation
bottom_footnotes = true

# Prose
smart_punctuation = true
render_emoji = true

# # Code
# highlight_code = true
# highlight_theme = "demain"
# error_on_missing_highlight = true
